name: Run Nightly Code Coverage
# Runs nightly at 00:00 UTC
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions: read-all

jobs:
  test-coverage:
    uses: Open-Systems-Pharmacology/Workflows/.github/workflows/test-coverage.yaml@main
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
